### ISSUE TITLE
Sitecode can contain numbers

### ISSUE THREAD

**Issue by mschilt** [PowerShellMafia/PowerSCCM#1]
My sitecode has one character and two digits.
After changing the regex in New-SccmSession() the connection was successful.
..
        [Parameter(Position = 1, Mandatory = $True)]
        [String]
        [ValidatePattern('^[A-Za-z0-9]{3}$')]
        $SiteCode,
..

**Comment by enigma0x3** [comment]
nice catch! I'll test this and update it.

Thanks!

**Comment by enigma0x3** [comment]
This has been fixed with commit https://github.com/PowerShellMafia/PowerSCCM/commit/6438d7b5c4a9909ce421eb3b1597de05abf5c6a8

Thanks again for catching this and providing the working regex.
